### ISSUE TITLE
Aceptar links

### ISSUE THREAD

**Issue by nmkdarango** [juanmicl/InstaResponder#1]
Hola Juan, gracias por este proyecto, lo usé y funcionó muy bien, apliqué una nueva funcionalidad dentro del proyecto local para permitir links:

en core/functions.php

	} elseif ($thread->items{0}->item_type == 'link') {
		$response = $dflow->query($thread->thread_id, $thread->last_permanent_item->link->text);
		$ig->direct->sendText(array(
			'thread' => $thread->thread_id),
			$response
		);
		
	}

Espero puedas aplicarlo en el proyecto actual, a muchas personas beneficia, saludos.

**Comment by juanmicl** [comment]
Añadido! https://github.com/juanmicl/InstaResponder/commit/18c5469a84064009e6ef04bcbe25f924aa3e77ac

Muchas gracias por tu aportación, también te recomiendo que aportes una estrella al proyecto para que pueda tener mayor visualización, gracias de antemano!

Siéntete libre para hacer cualquier cambio con pull requests :)
