### ISSUE TITLE
¿Como colaboro con el proyecto?

### ISSUE THREAD

**Issue by nmkdarango** [juanmicl/InstaResponder#2]
Creé un rama localmente, developer, e hice commit en esa rama, pero no sé como hacer el pull request. No se si es por falta de permisos, aunque tampoco comprendo bien cual sería el proceso, my skype es: danielarango90, si quieres conversamos, vivo en Colombia (creo que estamos a varias horas de diferencia). (Colombia = GTM-5)

**Comment by juanmicl** [comment]
Te acabo de agregar, seguimos en contacto por skype :)

**Comment by nmkdarango** [comment]
Listo!
